// Code generated by protoc-gen-go.
// source: bucket.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	bucket.proto
	types.proto

It has these top-level messages:
	Empty
	Selector
	NewBucket
	NewItem
	Item
	Node
	Tree
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Bucket service

type BucketClient interface {
	// Create a bucket
	Create(ctx context.Context, in *Selector, opts ...grpc.CallOption) (*Empty, error)
	// Put user data
	Put(ctx context.Context, in *NewItem, opts ...grpc.CallOption) (*Empty, error)
	// List the bucket content
	List(ctx context.Context, in *Selector, opts ...grpc.CallOption) (*Tree, error)
	// Get an item
	Get(ctx context.Context, in *Selector, opts ...grpc.CallOption) (*Item, error)
	// Delete an item
	Delete(ctx context.Context, in *Selector, opts ...grpc.CallOption) (*Empty, error)
}

type bucketClient struct {
	cc *grpc.ClientConn
}

func NewBucketClient(cc *grpc.ClientConn) BucketClient {
	return &bucketClient{cc}
}

func (c *bucketClient) Create(ctx context.Context, in *Selector, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/proto.Bucket/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bucketClient) Put(ctx context.Context, in *NewItem, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/proto.Bucket/Put", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bucketClient) List(ctx context.Context, in *Selector, opts ...grpc.CallOption) (*Tree, error) {
	out := new(Tree)
	err := grpc.Invoke(ctx, "/proto.Bucket/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bucketClient) Get(ctx context.Context, in *Selector, opts ...grpc.CallOption) (*Item, error) {
	out := new(Item)
	err := grpc.Invoke(ctx, "/proto.Bucket/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bucketClient) Delete(ctx context.Context, in *Selector, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/proto.Bucket/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Bucket service

type BucketServer interface {
	// Create a bucket
	Create(context.Context, *Selector) (*Empty, error)
	// Put user data
	Put(context.Context, *NewItem) (*Empty, error)
	// List the bucket content
	List(context.Context, *Selector) (*Tree, error)
	// Get an item
	Get(context.Context, *Selector) (*Item, error)
	// Delete an item
	Delete(context.Context, *Selector) (*Empty, error)
}

func RegisterBucketServer(s *grpc.Server, srv BucketServer) {
	s.RegisterService(&_Bucket_serviceDesc, srv)
}

func _Bucket_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Selector)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BucketServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Bucket/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BucketServer).Create(ctx, req.(*Selector))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bucket_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewItem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BucketServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Bucket/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BucketServer).Put(ctx, req.(*NewItem))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bucket_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Selector)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BucketServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Bucket/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BucketServer).List(ctx, req.(*Selector))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bucket_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Selector)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BucketServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Bucket/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BucketServer).Get(ctx, req.(*Selector))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bucket_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Selector)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BucketServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Bucket/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BucketServer).Delete(ctx, req.(*Selector))
	}
	return interceptor(ctx, in, info, handler)
}

var _Bucket_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Bucket",
	HandlerType: (*BucketServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Bucket_Create_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _Bucket_Put_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Bucket_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Bucket_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Bucket_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bucket.proto",
}

func init() { proto1.RegisterFile("bucket.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x2a, 0x4d, 0xce,
	0x4e, 0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x52, 0xdc, 0x25, 0x95,
	0x05, 0xa9, 0xc5, 0x10, 0x31, 0xa3, 0x2b, 0x8c, 0x5c, 0x6c, 0x4e, 0x60, 0x45, 0x42, 0x9a, 0x5c,
	0x6c, 0xce, 0x45, 0xa9, 0x89, 0x25, 0xa9, 0x42, 0xfc, 0x10, 0x49, 0xbd, 0xe0, 0xd4, 0x9c, 0xd4,
	0xe4, 0x92, 0xfc, 0x22, 0x29, 0x1e, 0xa8, 0x80, 0x6b, 0x6e, 0x41, 0x49, 0xa5, 0x12, 0x83, 0x90,
	0x2a, 0x17, 0x73, 0x40, 0x69, 0x89, 0x10, 0x1f, 0x54, 0xd8, 0x2f, 0xb5, 0xdc, 0xb3, 0x24, 0x35,
	0x17, 0x43, 0x99, 0x1a, 0x17, 0x8b, 0x4f, 0x66, 0x71, 0x09, 0xa6, 0x79, 0xdc, 0x50, 0x81, 0x90,
	0xa2, 0xd4, 0x54, 0x88, 0x71, 0xee, 0xa9, 0x78, 0x94, 0x81, 0x0c, 0x57, 0x62, 0x00, 0x39, 0xd0,
	0x25, 0x35, 0x27, 0x95, 0x08, 0x07, 0x26, 0xb1, 0x81, 0xb9, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xb5, 0x65, 0xc5, 0xb6, 0x01, 0x01, 0x00, 0x00,
}
