// Code generated by protoc-gen-go.
// source: deleter.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	deleter.proto
	getter.proto
	lister.proto
	saver.proto

It has these top-level messages:
	DeleteRequest
	DeleteReply
	GetRequest
	GetReply
	ListRequest
	ListReply
	SaveRequest
	SaveReply
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the bucket and key
type DeleteRequest struct {
	Bucket string `protobuf:"bytes,1,opt,name=bucket" json:"bucket,omitempty"`
	Key    string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto1.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// The response message containing the status
type DeleteReply struct {
	Status int32 `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
}

func (m *DeleteReply) Reset()                    { *m = DeleteReply{} }
func (m *DeleteReply) String() string            { return proto1.CompactTextString(m) }
func (*DeleteReply) ProtoMessage()               {}
func (*DeleteReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto1.RegisterType((*DeleteRequest)(nil), "proto.DeleteRequest")
	proto1.RegisterType((*DeleteReply)(nil), "proto.DeleteReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Deleter service

type DeleterClient interface {
	// Get an item
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteReply, error)
}

type deleterClient struct {
	cc *grpc.ClientConn
}

func NewDeleterClient(cc *grpc.ClientConn) DeleterClient {
	return &deleterClient{cc}
}

func (c *deleterClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteReply, error) {
	out := new(DeleteReply)
	err := grpc.Invoke(ctx, "/proto.Deleter/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Deleter service

type DeleterServer interface {
	// Get an item
	Delete(context.Context, *DeleteRequest) (*DeleteReply, error)
}

func RegisterDeleterServer(s *grpc.Server, srv DeleterServer) {
	s.RegisterService(&_Deleter_serviceDesc, srv)
}

func _Deleter_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeleterServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Deleter/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeleterServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Deleter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Deleter",
	HandlerType: (*DeleterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Delete",
			Handler:    _Deleter_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto1.RegisterFile("deleter.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 145 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x49, 0xcd, 0x49,
	0x2d, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x96, 0x5c,
	0xbc, 0x2e, 0x60, 0xf1, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x31, 0x2e, 0xb6, 0xa4,
	0xd2, 0xe4, 0xec, 0xd4, 0x12, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x28, 0x4f, 0x48, 0x80,
	0x8b, 0x39, 0x3b, 0xb5, 0x52, 0x82, 0x09, 0x2c, 0x08, 0x62, 0x2a, 0xa9, 0x72, 0x71, 0xc3, 0xb4,
	0x16, 0xe4, 0x54, 0x82, 0x34, 0x16, 0x97, 0x24, 0x96, 0x94, 0x16, 0x83, 0x35, 0xb2, 0x06, 0x41,
	0x79, 0x46, 0xf6, 0x5c, 0xec, 0x10, 0x65, 0x45, 0x42, 0x26, 0x5c, 0x6c, 0x10, 0xa6, 0x90, 0x08,
	0xc4, 0x15, 0x7a, 0x28, 0x76, 0x4b, 0x09, 0xa1, 0x89, 0x16, 0xe4, 0x54, 0x2a, 0x31, 0x24, 0xb1,
	0x81, 0x05, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x22, 0x7a, 0xd8, 0x7e, 0xc1, 0x00, 0x00,
	0x00,
}
