// Code generated by protoc-gen-go.
// source: types.proto
// DO NOT EDIT!

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Empty response.
type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto1.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

// The request message containing the path of a bucket or item.
type Selector struct {
	Path string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
}

func (m *Selector) Reset()                    { *m = Selector{} }
func (m *Selector) String() string            { return proto1.CompactTextString(m) }
func (*Selector) ProtoMessage()               {}
func (*Selector) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

// Bucket to be created at the given path.
type NewBucket struct {
	Path string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
}

func (m *NewBucket) Reset()                    { *m = NewBucket{} }
func (m *NewBucket) String() string            { return proto1.CompactTextString(m) }
func (*NewBucket) ProtoMessage()               {}
func (*NewBucket) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

// Item sent to be saved in the bucket.
type NewItem struct {
	Path string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *NewItem) Reset()                    { *m = NewItem{} }
func (m *NewItem) String() string            { return proto1.CompactTextString(m) }
func (*NewItem) ProtoMessage()               {}
func (*NewItem) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

// Item informations.
type Item struct {
	Key  string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *Item) Reset()                    { *m = Item{} }
func (m *Item) String() string            { return proto1.CompactTextString(m) }
func (*Item) ProtoMessage()               {}
func (*Item) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

// List of items.
type Items struct {
	Items []*Item `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *Items) Reset()                    { *m = Items{} }
func (m *Items) String() string            { return proto1.CompactTextString(m) }
func (*Items) ProtoMessage()               {}
func (*Items) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *Items) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto1.RegisterType((*Empty)(nil), "proto.Empty")
	proto1.RegisterType((*Selector)(nil), "proto.Selector")
	proto1.RegisterType((*NewBucket)(nil), "proto.NewBucket")
	proto1.RegisterType((*NewItem)(nil), "proto.NewItem")
	proto1.RegisterType((*Item)(nil), "proto.Item")
	proto1.RegisterType((*Items)(nil), "proto.Items")
}

func init() { proto1.RegisterFile("types.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xa9, 0x2c, 0x48,
	0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xec, 0x5c, 0xac, 0xae,
	0xb9, 0x05, 0x25, 0x95, 0x4a, 0x72, 0x5c, 0x1c, 0xc1, 0xa9, 0x39, 0xa9, 0xc9, 0x25, 0xf9, 0x45,
	0x42, 0x42, 0x5c, 0x2c, 0x05, 0x89, 0x25, 0x19, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60,
	0xb6, 0x92, 0x3c, 0x17, 0xa7, 0x5f, 0x6a, 0xb9, 0x53, 0x69, 0x72, 0x76, 0x6a, 0x09, 0x56, 0x05,
	0x86, 0x5c, 0xec, 0x7e, 0xa9, 0xe5, 0x9e, 0x25, 0xa9, 0xb9, 0xd8, 0xa4, 0x41, 0x62, 0x29, 0x89,
	0x25, 0x89, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x60, 0xb6, 0x92, 0x0e, 0x17, 0x0b, 0x58,
	0xbd, 0x00, 0x17, 0x73, 0x76, 0x6a, 0x25, 0x54, 0x39, 0x88, 0x89, 0x55, 0xb5, 0x16, 0x17, 0x2b,
	0x48, 0x75, 0xb1, 0x90, 0x22, 0x17, 0x6b, 0x26, 0x88, 0x21, 0xc1, 0xa8, 0xc0, 0xac, 0xc1, 0x6d,
	0xc4, 0x0d, 0xf1, 0x91, 0x1e, 0x48, 0x32, 0x08, 0x22, 0x93, 0xc4, 0x06, 0x16, 0x32, 0x06, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x25, 0x8d, 0x23, 0xf6, 0xf3, 0x00, 0x00, 0x00,
}
