// Code generated by protoc-gen-go.
// source: types.proto
// DO NOT EDIT!

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Empty response.
type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto1.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

// The request message containing the path of a bucket or item.
type Selector struct {
	Path      string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Recursive bool   `protobuf:"varint,2,opt,name=recursive" json:"recursive,omitempty"`
}

func (m *Selector) Reset()                    { *m = Selector{} }
func (m *Selector) String() string            { return proto1.CompactTextString(m) }
func (*Selector) ProtoMessage()               {}
func (*Selector) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

// Bucket to be created at the given path.
type NewBucket struct {
	Path string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
}

func (m *NewBucket) Reset()                    { *m = NewBucket{} }
func (m *NewBucket) String() string            { return proto1.CompactTextString(m) }
func (*NewBucket) ProtoMessage()               {}
func (*NewBucket) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

// Item sent to be saved in the bucket.
type NewItem struct {
	Path  string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *NewItem) Reset()                    { *m = NewItem{} }
func (m *NewItem) String() string            { return proto1.CompactTextString(m) }
func (*NewItem) ProtoMessage()               {}
func (*NewItem) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

// Item informations.
type Item struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *Item) Reset()                    { *m = Item{} }
func (m *Item) String() string            { return proto1.CompactTextString(m) }
func (*Item) ProtoMessage()               {}
func (*Item) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

// A Node can be either an item or a bucket.
type Node struct {
	Key      string  `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value    []byte  `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Children []*Node `protobuf:"bytes,3,rep,name=children" json:"children,omitempty"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto1.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *Node) GetChildren() []*Node {
	if m != nil {
		return m.Children
	}
	return nil
}

// Tree of Nodes.
type Tree struct {
	Children []*Node `protobuf:"bytes,1,rep,name=children" json:"children,omitempty"`
}

func (m *Tree) Reset()                    { *m = Tree{} }
func (m *Tree) String() string            { return proto1.CompactTextString(m) }
func (*Tree) ProtoMessage()               {}
func (*Tree) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *Tree) GetChildren() []*Node {
	if m != nil {
		return m.Children
	}
	return nil
}

func init() {
	proto1.RegisterType((*Empty)(nil), "proto.Empty")
	proto1.RegisterType((*Selector)(nil), "proto.Selector")
	proto1.RegisterType((*NewBucket)(nil), "proto.NewBucket")
	proto1.RegisterType((*NewItem)(nil), "proto.NewItem")
	proto1.RegisterType((*Item)(nil), "proto.Item")
	proto1.RegisterType((*Node)(nil), "proto.Node")
	proto1.RegisterType((*Tree)(nil), "proto.Tree")
}

func init() { proto1.RegisterFile("types.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xa9, 0x2c, 0x48,
	0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xec, 0x5c, 0xac, 0xae,
	0xb9, 0x05, 0x25, 0x95, 0x4a, 0x36, 0x5c, 0x1c, 0xc1, 0xa9, 0x39, 0xa9, 0xc9, 0x25, 0xf9, 0x45,
	0x42, 0x42, 0x5c, 0x2c, 0x05, 0x89, 0x25, 0x19, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60,
	0xb6, 0x90, 0x0c, 0x17, 0x67, 0x51, 0x6a, 0x72, 0x69, 0x51, 0x71, 0x66, 0x59, 0xaa, 0x04, 0x93,
	0x02, 0xa3, 0x06, 0x47, 0x10, 0x42, 0x40, 0x49, 0x9e, 0x8b, 0xd3, 0x2f, 0xb5, 0xdc, 0xa9, 0x34,
	0x39, 0x3b, 0xb5, 0x04, 0x9b, 0x76, 0x25, 0x63, 0x2e, 0x76, 0xbf, 0xd4, 0x72, 0xcf, 0x92, 0xd4,
	0x5c, 0xac, 0xa6, 0x8b, 0x70, 0xb1, 0x96, 0x25, 0xe6, 0x94, 0x42, 0x4c, 0xe6, 0x09, 0x82, 0x70,
	0x94, 0xf4, 0xb8, 0x58, 0xc0, 0x3a, 0x04, 0xb8, 0x98, 0xb3, 0x53, 0x2b, 0xa1, 0x1a, 0x40, 0x4c,
	0x1c, 0xea, 0xc3, 0xb9, 0x58, 0xfc, 0xf2, 0x53, 0x52, 0x89, 0x55, 0x2f, 0xa4, 0xce, 0xc5, 0x91,
	0x9c, 0x91, 0x99, 0x93, 0x52, 0x94, 0x9a, 0x27, 0xc1, 0xac, 0xc0, 0xac, 0xc1, 0x6d, 0xc4, 0x0d,
	0x09, 0x1d, 0x3d, 0x90, 0x31, 0x41, 0x70, 0x49, 0x25, 0x7d, 0x2e, 0x96, 0x90, 0xa2, 0x54, 0x54,
	0x0d, 0x8c, 0x78, 0x34, 0x24, 0xb1, 0x81, 0x45, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6c,
	0x69, 0x3b, 0x88, 0x73, 0x01, 0x00, 0x00,
}
